import { useState } from "react";
import { DiagnosticResult } from "../types";
import { FileDown, Clipboard, Check, Sparkles, Code } from "lucide-react";

interface PostmortemGenProps {
  diagnostic: DiagnosticResult | null;
  incidentName: string;
}

export function PostmortemGen({ diagnostic, incidentName }: PostmortemGenProps) {
  const [copied, setCopied] = useState(false);

  if (!diagnostic) {
    return null;
  }

  const generateMarkdown = () => {
    const timestampStr = new Date().toUTCString();
    return `
# INCIDENT POSTMORTEM (POST-MORTEM REPORT)
**Incident Name:** ${incidentName || "Unscheduled Component Outage"}
**Report Generated:** ${timestampStr}
**Status:** MITIGATED

---

## 1. Executive Summary
### Incident Overview
${diagnostic.summary}

### Key Metrics
* **Incident Severity:** ${diagnostic.severity.toUpperCase()}
* **Detection Mechanism:** TRAVIX Outage Predictor Core (AI-driven)
* **Confidence Level:** ${diagnostic.confidence}% SRE index
* **Estimated Impact Radius:** ${diagnostic.affectedUsers}
* **Causality Origin:** ${diagnostic.probableRootCause}

---

## 2. Root Cause Analysis
### Anomaly Pattern Detected
The AI identified a fault signature indicating failure in \`${diagnostic.probableRootCause}\`. 

### Topology Propagation Chain
${diagnostic.failurePropagation.map((line, idx) => `Step ${idx + 1}: \`${line.source}\` → \`${line.target}\` via [${line.connectionState}] (Status: \`${line.status.toUpperCase()}\`)`).join("\n")}

---

## 3. Timeline / Chronic Chronology
* **T+00:00 (Incident Trigger):** Systems detected metric anomaly matching baseline limits.
* **T+01:30 (Correlation):** TRAVIX automatically mapped logs and isolated latency spikes.
* **T+02:45 (Triage):** Auto-RCA computed the probable root cause as \`${diagnostic.probableRootCause}\` with matching confidence score of ${diagnostic.confidence}%.
* **T+04:15 (Resolution Recommendation):** Generated resolution guides. Playbooks delivered of Slack channel.

---

## 4. Remediation and Suggested Fixes
Execute these instructions immediately to restore full system stability:
${diagnostic.suggestedFixes.map((fix) => `* \`${fix}\``).join("\n")}

---

## 5. Prevention Strategy & Recurring Match
This incident matches previous outages like **"${diagnostic.memoryMatch.eventName}"** by **${diagnostic.memoryMatch.similarityPercentage}**. 
${diagnostic.memoryMatch.recurringPatterns}

### Recommended Actions to Prevent Regressions
1. Enforce aggressive circuit breaker timeouts on \`${diagnostic.probableRootCause}\` connections.
2. Implement strict rate-limiting policies at API Gateway.
3. Establish robust OOM threshold parameters with automatic alert routing.

---
*Report proudly generated by TRAVIX – Turning Chaos Into Clarity.*
`;
  };

  const handleCopyMarkdown = () => {
    const markdown = generateMarkdown();
    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `TRAVIX-postmortem-${incidentName.toLowerCase().replace(/\s+/g, "-")}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900/40 border border-slate-800 rounded-xl p-6 glow-purple mt-6 relative overflow-hidden shadow-[0_0_12px_rgba(168,85,247,0.05)]">
      {/* Absolute graphic background */}
      <div className="absolute top-0 left-0 w-32 h-32 bg-purple-500/5 rounded-full blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4 pb-4 border-b border-slate-800/80">
        <div>
          <h2 className="text-sm font-bold tracking-widest text-purple-400 font-mono flex items-center gap-2">
            <Sparkles className="w-4 h-4 animate-pulse text-purple-300" />
            AI-GENERATED POSTMORTEM REPORT
          </h2>
          <p className="text-xs text-slate-400 mt-1">SRE Postmortem documentation generated in Markdown format</p>
        </div>
        <div className="flex gap-2 shrink-0 font-mono">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg bg-slate-950 border border-slate-800 text-slate-300 hover:text-white hover:border-slate-700 transition cursor-pointer"
          >
            {copied ? (
              <span className="flex items-center gap-1.5 text-emerald-400">
                <Check className="w-3.5 h-3.5" /> Copied!
              </span>
            ) : (
              <span className="flex items-center gap-1.5">
                <Clipboard className="w-3.5 h-3.5 text-slate-400" /> Copy Report
              </span>
            )}
          </button>
          <button
            onClick={handleDownloadMarkdown}
            className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded bg-purple-600 border border-purple-500 text-white hover:bg-purple-500 transition shadow-[0_0_10px_rgba(168,85,247,0.2)]"
          >
            <FileDown className="w-3.5 h-3.5" /> Save .md File
          </button>
        </div>
      </div>

      {/* Embedded Document Previewer */}
      <div className="bg-slate-950/85 border border-slate-850 rounded-lg p-5 font-mono text-xs max-h-[350px] overflow-y-auto space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800/60 pb-2 mb-3 text-[10px] text-slate-500">
          <span className="flex items-center gap-1.5"><Code className="w-3.5 h-3.5 text-slate-500" /> postmortem_report.md</span>
          <span>MITIGATED STATE</span>
        </div>
        <div className="space-y-4 text-slate-300 leading-relaxed max-w-none">
          <h1 className="text-sm font-bold text-slate-100 border-b border-slate-900 pb-1"># INCIDENT POSTMORTEM SUMMARY: {incidentName}</h1>
          <p className="italic text-slate-400">"SRE auto-diagnosis completed. Root cause isolated at database/caching border elements immediately."</p>
          
          <div>
            <h3 className="font-bold text-slate-150 uppercase tracking-widest text-[10px] text-purple-400">## 1. Executive Summary</h3>
            <p className="mt-1 pl-3 border-l border-slate-800 whitespace-pre-line text-[11px] font-sans">
              {diagnostic.summary}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-2 p-3 bg-slate-900/40 rounded border border-slate-850 text-[11px]">
            <div>• <b>Cause Node:</b> {diagnostic.probableRootCause}</div>
            <div>• <b>Severity:</b> {diagnostic.severity.toUpperCase()}</div>
            <div>• <b>Confidence Index:</b> {diagnostic.confidence}%</div>
            <div>• <b>Impact:</b> {diagnostic.affectedUsers}</div>
          </div>

          <div>
            <h3 className="font-bold text-slate-150 uppercase tracking-widest text-[10px] text-purple-400">## 2. Actionable Playbook Execution</h3>
            <p className="text-[10px] text-slate-400 mt-0.5">Run these SRE resolution actions to stabilize clusters immediately:</p>
            <ul className="mt-1 space-y-1 list-disc list-inside text-[11px] leading-relaxed font-sans text-slate-200">
              {diagnostic.suggestedFixes.map((fix, idx) => (
                <li key={idx}><code>{fix}</code></li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
